### ISSUE TITLE
binaries?

### ISSUE THREAD

**Issue by roelofr** [twittemb/StreamIt#3]
I dug out an old iPhone I no longer use, and was wondering if there are any binaries available for this app, since I don't own a mac to compile my own.

(It's an iPhone 5, I don't even know if this supports it 🙊 )

**Comment by GabLeRoux** [comment]
App distribution needs to be signed by apple for public use. There are other distribution apps ex; for beta testing, but I don't think its easy enough. In other words, if it's not on the app store, you'll have to build it yourself and trust yourself in the settings app.

If you don't have a mac, I see another way to bypass this and it would be to use something like [github actions](https://github.com/features/actions) to [build an ios app](https://engineering.talkdesk.com/test-and-deploy-an-ios-app-with-github-actions-44de9a7dcef6).

Won't work on first try as the result still needs to be signed which usually requires an apple developer account, but maybe someone have an idea to make this work.

btw, If you're not an apple developer, you might have better luck with Android devices which is much more accessible. ;)

**Comment by roelofr** [comment]
Hey, thanks for getting back to this.

It was a bit of an ad-hoc solution, since it was just when the real lockdown-crazyness started, and I hadn't discovered stuff like DroidcamX yet. I eventually switched to using my own Android phone as a webcam, which I replaced with a far to expensive webcam (yay for covid-upmarking) in september or something.

I'll close this now, best of luck this year!
