### ISSUE TITLE
No such module 'CocoaAsyncSocket'

### ISSUE THREAD

**Issue by CallMeTuesday** [twittemb/StreamIt#4]
Appears in xcode 11.3.1
Downloaded source, tried to run, got error
Attempting to install on an iPhone X Pro

**Comment by NeatKoala** [comment]
Use Carthage to download dependencies:
https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

**Comment by twittemb** [comment]
carthage bootstrap —platform iOS
