### ISSUE TITLE
Memory limit crash

### ISSUE THREAD

**Issue by dylancom** [twittemb/StreamIt#6]
During testing on a device I've noticed that many times the app will crash due to "Memory Limit".
In Xcode I see the memory increasing over time until this limit is reached.
Is there something to prevent this? Clearing resources, changing the frame rate...

**Comment by twittemb** [comment]
Hi

I’ve tried it today and the mem was constantly under 50 Mo.

What is the amont of time before a crash ?

Thibault Wittemberg

**Comment by dylancom** [comment]
Hmm sorry for the inconvenience. Seems to work fine now and staying around 30MB.
I did find though that if you refresh browser a couple of times, the stream doesn't work anymore.

**Comment by dylancom** [comment]
@twittemb I found what's causing this. If you start the app and open the IP URL in Chrome, it works fine. If you then stop the app, start the app again and "refresh" the **already open IP URL** in Chrome, the memory will start to increase and increase.
Seems something todo with an already previously opened socket.

**Comment by twittemb** [comment]
Thanks for the investigation. Would be interested in making a PR to fix that ?

**Comment by dylancom** [comment]
@twittemb Interested for sure, haven't found yet how to fix it though.

**Comment by dylancom** [comment]
@twittemb found out that the problem is gone after changing all socket write timeouts from -1 to 1. Not sure what should be a correct setting...

**Comment by jhollowayj** [comment]
My best guess is that it's related to the map of clients using only the ip address in [here](https://github.com/twittemb/StreamIt/blob/master/StreamIt/CameraViewController.swift#L242-L246)
